engines:
  fixme:
    enabled: true  
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:

 
ratings:
   paths:
   - "e2e/**.js"
   - "src/**.js"
   - "public/**.js"
   - "**.jsx"
   - "public/**.css"

exclude_paths:
- "bower_components/"
- "node_modules/"
- "React-based Elements/"
      
