engines: 
  eslint:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: false
    
ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"

exclude_paths:
- "bower_components/"
- "node_modules/"
      
