engines:
  eslint:
    enabled: true
    exclude_paths:
    - bower_components/*
  csslint:
    enabled: true
    exclude_paths:
    - bower_components/*
  duplication:
    enabled: false
    exclude_paths:
    - bower_components/*

ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"

exclude_paths:
- bower_components/*
