engines:
  eslint:
    enabled: true
  tslint:
    enabled: true
    channel: beta
  csslint:
    enabled: true
  duplication:
    enabled: false
 
ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"

exclude_paths:
- "bower_components/"
- "node_modules/"
      
