dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm update
  - bower update
  - npm install
  - npm install nsp --global
  - bower install 
script:
  - npm run lint
  - npm run test:once
  - npm run e2e
  - npm run build
  - npm run preprotractor
 
notifications:
    slack: cryptostewarts:KJp9hwkuiYYblcNjDcLfF159

    
    
